# Generated by Django 3.1.4 on 2021-03-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechMelba_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='member_github',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
