# Generated by Django 3.1.4 on 2021-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechMelba_App', '0002_teammember_member_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successstory',
            old_name='story_title',
            new_name='story_client_desig',
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='story_image',
            new_name='story_client_image',
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='story_message',
            new_name='story_client_message',
        ),
        migrations.AddField(
            model_name='successstory',
            name='story_client_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
