# Generated by Django 3.1.4 on 2021-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechMelba_App', '0003_auto_20210316_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
