# Generated by Django 3.1.4 on 2021-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechMelba_App', '0004_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
