# Generated by Django 3.1.4 on 2021-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechMelba_App', '0005_projects_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_site_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_tool_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
